[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/status"
healthcheckTimeout = 100
healthcheckInterval = 10

[[services]]
name = "api"

[services.variables]
NODE_ENV = "production"
PORT = "3000"

[nixpacks]
npm-omit-dev = true